### ISSUE TITLE
nuxt3-shadcn-main doesn't compile

### ISSUE THREAD

**Issue by gilles6** [guillaumeduhan/nuxt3-shadcn#2]
Hi Guillaume,
It doesn't seem to compile...
```
~/Downloads/nuxt3-shadcn-main ❯ pnpm install
 WARN  7 deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@8.1.0, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Packages: +873
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 948, reused 873, downloaded 0, added 873, done

> nuxt-app@ postinstall /Users/me/Downloads/nuxt3-shadcn-main
> nuxt prepare

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css

 ERROR  Error while requiring module nuxt-highcharts: Error: ENOENT: no such file or directory, scandir '/Users/me/Downloads/nuxt3-shadcn-main/node_modules/highcharts/modules'


 ERROR  ENOENT: no such file or directory, scandir '/Users/me/Downloads/nuxt3-shadcn-main/node_modules/highcharts/modules'

  at readdirSync (node:fs:1509:26)
  at node_modules/.pnpm/nuxt-highcharts@3.1.1/node_modules/nuxt-highcharts/lib/module.js:13:36
  at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
  at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.12.2_magicast@0.3.4_rollup@4.18.0/node_modules/@nuxt/kit/dist/index.mjs:2234:26)
  at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.12.2_magicast@0.3.4_rollup@4.18.0/node_modules/@nuxt/kit/dist/index.mjs:2509:92)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.12.2_magicast@0.3.4_rollup@4.18.0/node_modules/@nuxt/kit/dist/index.mjs:2461:47)
  at async initNuxt (node_modules/.pnpm/nuxt@3.12.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_bym274y7e6pdtqyb2d2a2kjo5m/node_modules/nuxt/dist/index.mjs:4395:5)
  at async loadNuxt (node_modules/.pnpm/nuxt@3.12.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_bym274y7e6pdtqyb2d2a2kjo5m/node_modules/nuxt/dist/index.mjs:4525:5)
  at async loadNuxt (node_modules/.pnpm/@nuxt+kit@3.12.2_magicast@0.3.4_rollup@4.18.0/node_modules/@nuxt/kit/dist/index.mjs:2651:19) 



 ERROR  ENOENT: no such file or directory, scandir '/Users/me/Downloads/nuxt3-shadcn-main/node_modules/highcharts/modules'

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Bazsmagister** [comment]
This way worked for me:

remove `node_modules` dir

add into `package.json`:

```json
"dependencies": {
  "@tanstack/vue-table": "^8.17.3",
  "@vueuse/core": "^10.11.0"
},
"devDependencies": {
  "rollup": "^4.18.0"
}
```

`npm i`

`npm run dev`

**Comment by sabahmax-dev** [comment]
Thanks for flagging this! I’ve opened PR #3 to fix the compilation error. It addresses the issue where `nuxt-highcharts` tries to access a missing `highcharts/modules` directory during install, which was causing `nuxt prepare` to fail.
